#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
test -f /run/postgresql/postgres.run
pg_ctl status
if [ -n "$PG_AUTOCTL" ]; then
    FORMATION="$(pg_autoctl config get pg_autoctl.formation)"
    GROUP="$(pg_autoctl config get pg_autoctl.group)"
    HOST="$(pg_autoctl show state --group "$GROUP" --formation "$FORMATION" --json | jq --unbuffered --raw-output ".[] | select(.current_group_state == \"primary\" or .current_group_state == \"single\") | .nodehost")"
    PORT="$(pg_autoctl show state --group "$GROUP" --formation "$FORMATION" --json | jq --unbuffered --raw-output ".[] | select(.current_group_state == \"primary\" or .current_group_state == \"single\") | .nodeport")"
    echo "* = host=$HOST port=$PORT" >"$HOME/.databases.ini"
else
    echo "* = " >"$HOME/.databases.ini"
fi
