#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
test -f /run/postgresql/postgres.run
pg_ctl status
if [ -n "$PG_AUTO_FAILOVER" ]; then
    echo "* = $(pg_autoctl show uri --formation "$(pg_autoctl config get pg_autoctl.formation)" --json | jq -r ."$(pg_autoctl config get pg_autoctl.formation)")" >"$HOME/databases.ini"
else
    echo "* = " >"$HOME/databases.ini"
fi
