#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
touch "$HOME/databases.ini"
cat >"$HOME/pgbouncer.ini" <<EOF
[pgbouncer]
admin_users = postgres
application_name_add_host = 1
auth_hba_file = $(echo -n "$PGDATA")/pg_hba.conf
auth_type = hba
auth_user = postgres
listen_addr = *
listen_port = 5433
log_stats = 0
stats_users = postgres
unix_socket_dir = /run/postgresql
unix_socket_group = postgres
unix_socket_mode = 0777
EOF

if [ -d /etc/certs ]; then
    cat >>"$HOME/pgbouncer.ini" <<EOF

client_tls_ca_file = /etc/certs/ca.pem
client_tls_cert_file = /etc/certs/cert.pem
client_tls_key_file = /etc/certs/key.pem
client_tls_sslmode = prefer
server_tls_ca_file = /etc/certs/ca.pem
server_tls_cert_file = /etc/certs/cert.pem
server_tls_key_file = /etc/certs/key.pem
server_tls_sslmode = prefer
EOF
fi

cat >>"$HOME/pgbouncer.ini" <<EOF
[databases]
%include $(echo -n "$HOME")/databases.ini
EOF
