#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
cat >"$BACKUP_PATH/pg_rman.ini" <<EOF

ARCLOG_PATH='$(echo -n "$HOME")/pg_arclog'
COMPRESS_DATA=true
KEEP_ARCLOG_DAYS=1
KEEP_DATA_GENERATIONS=9
KEEP_SRVLOG_DAYS=1
SRVLOG_PATH='$(echo -n "$HOME")/pg_log'
WITH_SERVERLOG=true
EOF
cat >>"$BACKUP_PATH/pg_rman.ini" <<EOF

STANDBY_HOST=localhost
STANDBY_PORT=5432
EOF
test -f "$PGDATA/standby.signal" || cat >>"$PGDATA/postgresql.conf" <<EOF

archive_cleanup_command = 'pg_archivecleanup -d "$(echo -n "$HOME")/pg_arclog" "%r" 2>>"$(echo -n "$HOME")/pg_log/pg_archivecleanup.log"'
archive_command = 'test ! -f "$(echo -n "$HOME")/pg_arclog/%f" && cp "%p" "$(echo -n "$HOME")/pg_arclog/%f"'
archive_mode = on
log_directory = '$(echo -n "$HOME")/pg_log'
log_filename = 'postgresql-%Y-%m-%d.log'
logging_collector = on
log_truncate_on_rotation = on
max_wal_senders = 10
wal_level = replica
EOF
sv force-restart postgres
