#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
if [ -n "$PG_AUTOCTL" ] && [ "$(pg_autoctl config get pg_autoctl.role)" != "monitor" ]; then
    FORMATION="$(pg_autoctl config get pg_autoctl.formation)"
    GROUPID="$(pg_autoctl config get pg_autoctl.group)"
    NODEHOST="$(hostname)"
    NODENAME="$(pg_autoctl config get pg_autoctl.name)"
    STATE="$(pg_autoctl show state --group "$GROUPID" --formation "$FORMATION" --json | jq --unbuffered --raw-output ".[] | select(.nodename == \"$NODENAME\" and .nodehost == \"$NODEHOST\") | .current_group_state")"
    case "$STATE" in
        "single" | "primary" | "wait_primary")
            pg_rman backup --backup-mode=full
        ;;
#        "secondary")
#            HOST="$(pg_autoctl show state --group "$GROUPID" --formation "$FORMATION" --json | jq --unbuffered --raw-output ".[] | select(.current_group_state == \"primary\") | .nodehost")"
#            pg_rman backup --backup-mode=full --host="$HOST"
#        ;;
        *)
            exit
        ;;
    esac
else
    pg_rman backup --backup-mode=full
fi
pg_rman validate
pg_rman purge
