#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
pg_rman init
/etc/service/cron/conf
case "$(pg_autoctl config get pg_autoctl.role)" in
    "monitor" )
        cat >"$HOME/crontab" <<EOF
0   0   *   *   *  /etc/service/cron/full
0   1-23   *   *   *  /etc/service/cron/incremental
EOF
    ;;
    * )
        cat >"$HOME/crontab" <<EOF
0   0   *   *   0  /etc/service/cron/full
0   0   *   *   1-6  /etc/service/cron/incremental
EOF
    ;;
esac
