#!/bin/sh

exec 2>&1
install -d -m 1775 -o "$USER" -g "$GROUP" /run/postgresql
test -f /run/postgresql/postgres.run || exit $?
chpst -u "$USER":"$GROUP" pg_isready || exit $?
chpst -u "$USER":"$GROUP" pg_ctl status || exit $?
realpath "$0"
set -ex
test -f "$BACKUP_PATH/system_identifier" || chpst -u "$USER":"$GROUP" /etc/service/cron/init
test -f "$HOME/.crontab" || chpst -u "$USER":"$GROUP" /etc/service/cron/crontab
chpst -u "$USER":"$GROUP" crontab "$HOME/.crontab"
exec crond -d 8 -f
