#!/bin/sh

exec 2>&1
install -d -m 1775 -o "$USER" -g "$GROUP" /run/postgresql
test -f /run/postgresql/postgres.run || exit $?
chpst -u "$USER":"$GROUP" pg_isready || exit $?
chpst -u "$USER":"$GROUP" pg_ctl status || exit $?
chmod 755 supervise
chown "$USER":"$GROUP" supervise/ok supervise/control supervise/status
realpath "$0"
set -ex
FORMATION="$(chpst -u "$USER":"$GROUP" pg_autoctl config get pg_autoctl.formation)"
GROUPID="$(chpst -u "$USER":"$GROUP" pg_autoctl config get pg_autoctl.group)"
while true; do
    case "$(chpst -u "$USER":"$GROUP" pg_autoctl show state --group "$GROUPID" --formation "$FORMATION" --json --local | jq --unbuffered --raw-output .current_group_state)" in
        "single" | "primary" | "wait_primary")
            break
        ;;
        "secondary")
            chpst -u "$USER":"$GROUP" pg_autoctl perform switchover
        ;;
        *)
            sleep 10
        ;;
    esac
done
exec rm -rf /etc/service/primary
