#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
if [ -n "$PG_AUTOCTL_AUTH" ]; then AUTH="--auth $PG_AUTOCTL_AUTH"; else SKIP_PG_HBA="--skip-pg-hba"; fi
if [ -n "$PG_AUTOCTL_SERVER_CERT" ]; then SERVER_CERT="--server-cert $PG_AUTOCTL_SERVER_CERT"; fi
if [ -n "$PG_AUTOCTL_SERVER_KEY" ]; then SERVER_KEY="--server-key $PG_AUTOCTL_SERVER_KEY"; fi
if [ -n "$PG_AUTOCTL_SSL_CA_FILE" ]; then SSL_CA_FILE="--ssl-ca-file $PG_AUTOCTL_SSL_CA_FILE"; fi
if [ -n "$PG_AUTOCTL_SSL_CRL_FILE" ]; then SSL_CRL_FILE="--ssl-crl-file $PG_AUTOCTL_SSL_CRL_FILE"; fi
if [ -z "$SERVER_CERT" ] && [ -z "$SERVER_KEY" ]; then NO_SSL="--no-ssl"; fi
if [ -n "$PG_AUTOCTL_MONITOR" ]; then
    pg_isready -d "$PG_AUTOCTL_MONITOR"
    if [ "$(pg_autoctl get formation number-sync-standbys --formation "${PG_AUTOCTL_FORMATION:-default}" | wc -l)" -eq "0" ]; then
        pg_autoctl create formation --formation "${PG_AUTOCTL_FORMATION:-default}" --kind pgsql
    fi
    pg_autoctl create postgres \
        $AUTH \
        $NO_SSL \
        $SERVER_CERT \
        $SERVER_KEY \
        $SKIP_PG_HBA \
        $SSL_CA_FILE \
        $SSL_CRL_FILE \
        --formation "${PG_AUTOCTL_FORMATION:-default}" \
        --monitor "$PG_AUTOCTL_MONITOR" \
        --name "${PG_AUTOCTL_NAME:-$(hostname)}" \
        --replication-quorum "${PG_AUTOCTL_REPLICATION_QUORUM:-true}" \
        --ssl-mode "${PG_AUTOCTL_SSL_MODE:-allow}"
else
    pg_autoctl create monitor \
        $AUTH \
        $NO_SSL \
        $SERVER_CERT \
        $SERVER_KEY \
        $SKIP_PG_HBA \
        $SSL_CA_FILE \
        $SSL_CRL_FILE \
        --ssl-mode "${PG_AUTOCTL_SSL_MODE:-allow}"
fi
