#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
cat >>"$PGDATA/postgresql.conf" <<EOF

listen_addresses = '*'
max_logical_replication_workers = 0
max_sync_workers_per_subscription = 0
max_wal_senders = 0
wal_level = minimal
EOF

if [ -d /etc/certs ]; then
    cat >>"$PGDATA/postgresql.conf" <<EOF

ssl_ca_file = '/etc/certs/ca.pem'
ssl_cert_file = '/etc/certs/cert.pem'
ssl_crl_file = '/etc/certs/crl.pem'
ssl_key_file = '/etc/certs/key.pem'
ssl = on
EOF
fi
