#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
echo >>"$PGDATA/pg_hba.conf"
ip -o -f inet addr show | awk '/scope global/ {print $4}' | sed -E 's|.\d+/|.0/|' | while read -r NET; do
    echo "host all all $NET trust"
    if [ -n "$PG_AUTO_FAILOVER" ]; then
        echo "host replication all $NET trust"
    fi
done >>"$PGDATA/pg_hba.conf"
