#!/bin/sh

exec 2>&1
realpath "$0"
set -ex
if [ -d "$HOME/pg_rman" ] && [ "$(pg_rman show detail -a | grep OK | wc -l)" -gt "0" ]; then
    pg_rman restore
else
    if [ -d /etc/certs ]; then
        if [ -f /etc/certs/crl.pem ]; then
            SSL="--ssl-mode prefer --ssl-ca-file /etc/certs/ca.pem --ssl-crl-file /etc/certs/crl.pem --server-key /etc/certs/key.pem --server-cert /etc/certs/cert.pem"
        else
            SSL="--ssl-mode prefer --ssl-ca-file /etc/certs/ca.pem --server-key /etc/certs/key.pem --server-cert /etc/certs/cert.pem"
        fi
    else
        SSL="--no-ssl"
    fi
    if [ -z "$PG_AUTOCTL" ]; then
        cd "$PGDATA" && initdb
    elif [ -n "$PG_AUTOCTL_MONITOR" ]; then
        pg_autoctl create postgres --hostname "$(hostname)" --replication-quorum "${PG_AUTOCTL_REPLICATION_QUORUM:-true}" --formation "${PG_AUTOCTL_FORMATION:-default}" --name "${PG_AUTOCTL_NAME:-$(hostname)}" $SSL --skip-pg-hba --monitor="$PG_AUTOCTL_MONITOR"
    else
        pg_autoctl create monitor --hostname "$(hostname)" $SSL --skip-pg-hba
    fi
    if [ ! -f "$PGDATA/standby.signal" ]; then
        /etc/service/postgres/conf
        /etc/service/postgres/hba
    fi
fi
