#!/bin/sh

exec 2>&1
if [ -n "$PG_AUTOCTL" ]; then install -d -m 1775 -o "$USER" -g "$GROUP" "/tmp/pg_autoctl"
else install -d -m 0750 -o "$USER" -g "$GROUP" "$PGDATA"; fi
install -d -m 1775 -o "$USER" -g "$GROUP" /run/postgresql /var/log/postgresql
if [ "$(pgrep runsvdir | wc -l)" -gt "0" ]; then
    install -d -m 0750 -o "$USER" -g "$GROUP" "$HOME/pg_arclog" "$HOME/pg_log" "$HOME/pg_rman"
    chmod 755 supervise
    chown "$USER":"$GROUP" supervise/ok supervise/control supervise/status
fi
rm -f /run/postgresql/postgres.run "$PGDATA/postmaster.pid"
realpath "$0"
set -ex
test -d "$PGDATA/base" || chpst -u "$USER":"$GROUP" /etc/service/postgres/init
test -d "$PGDATA/base"
if [ -n "$PG_AUTOCTL" ]; then
    if [ -n "$PG_AUTOCTL_MONITOR" ]; then
        if [ -f "$HOME/.config/pg_autoctl$PGDATA/pg_autoctl.cfg" ]; then
            chpst -u "$USER":"$GROUP" pg_isready -d "$PG_AUTOCTL_MONITOR"
            FORMATION="$(chpst -u "$USER":"$GROUP" pg_autoctl config get pg_autoctl.formation)"
            GROUPID="$(chpst -u "$USER":"$GROUP" pg_autoctl config get pg_autoctl.group)"
            NODEHOST="$(hostname)"
            NODENAME="$(chpst -u "$USER":"$GROUP" pg_autoctl config get pg_autoctl.name)"
            if [ "$(chpst -u "$USER":"$GROUP" pg_autoctl show state --group "$GROUPID" --formation "$FORMATION" --json | jq --unbuffered --raw-output ".[] | select(.nodename == \"$NODENAME\" and .nodehost == \"$NODEHOST\") | .nodename" | wc -l)" -eq "0" ]; then
                chpst -u "$USER":"$GROUP" pg_autoctl drop node
                rm -f "$HOME/.config/pg_autoctl$PGDATA/pg_autoctl.cfg"
            fi
        fi
        if [ ! -f "$HOME/.primary" ]; then
            rm -rf /etc/service/primary
        fi
    else
        rm -rf /etc/service/pgbouncer
        rm -rf /etc/service/primary
    fi
    if [ ! -f "$HOME/.config/pg_autoctl$PGDATA/pg_autoctl.cfg" ]; then
        chpst -u "$USER":"$GROUP" /etc/service/postgres/autoctl
    fi
    exec chpst -u "$USER":"$GROUP" -L /run/postgresql/postgres.run pg_autoctl run
else
    rm -rf /etc/service/pglisten
    rm -rf /etc/service/primary
    exec chpst -u "$USER":"$GROUP" -L /run/postgresql/postgres.run postmaster
fi
