#!/bin/sh

exec 2>&1
install -d -m 1775 -o "$USER" -g "$GROUP" /run/postgresql /var/log/postgresql
chmod 755 supervise
chown "$USER":"$GROUP" supervise/ok supervise/control supervise/status
realpath "$0"
set -ex
rm -f "$PGDATA/postmaster.pid"
if [ ! -d "$PGDATA/base" ]; then
    if [ -z "$PG_AUTO_FAILOVER_MONITOR" ]; then
        chpst -u "$USER":"$GROUP" pg_autoctl -vvv create monitor --hostname "$(hostname)" --no-ssl --skip-pg-hba
    else
        chpst -u "$USER":"$GROUP" pg_autoctl -vvv create postgres --hostname "$(hostname)" --name "$(hostname)" --no-ssl --skip-pg-hba --monitor="$PG_AUTO_FAILOVER_MONITOR"
    fi
    if [ ! -f "$PGDATA/standby.signal" ]; then
        chpst -u "$USER":"$GROUP" /etc/service/postgres/conf
        chpst -u "$USER":"$GROUP" /etc/service/postgres/hba
    fi
fi
test -d "$PGDATA/base"
exec chpst -u "$USER":"$GROUP" pg_autoctl -vvv run
